insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Bola de Futebol', 83.72, '10cmx40cmx5cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Bola de Vôlei', 66.95, '4mx1mx3m');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Bola de Tênis', 25.14, '8cmx2cmx2cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Bola de Basquete', 8.86, '21cmx52cmx41cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Raquete', 62.68, '88cmx22cmx33cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Vara', 82.06, '10cmx40cmx5cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Remo', 11.59, '15cmx30cmx50cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Caiaque', 22.08, '21cmx52cmx41cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Rede', 44.53, '21cmx52cmx41cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Viga de Aço', 88.62, '1mx1mx1m');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Medicamentos', 73.24, '500cmx300cmx215cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Salgados', 2.32, '21cmx52cmx41cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Laranja', 42.62, '6cmx90cmx10cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Pêra', 59.8, '4mx1mx3m');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Maçã', 77.58, '45cmx60cmx1cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Abacaxi', 78.99, '21cmx52cmx41cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Pêssego', 48.59, '8cmx2cmx2cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Vassoura', 39.7, '10cmx40cmx5cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Rodo', 7.43, '8cmx2cmx2cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Alvejante', 12.37, '21cmx52cmx41cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Água Sanitária', 58.03, '6cmx90cmx10cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Cloro', 20.07, '8cmx2cmx2cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Esfregão', 16.52, '88cmx22cmx33cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Panos', 19.58, '1mx1mx1m');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Rastelo', 32.84, '29cmx81cmx100cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Uniforme', 74.75, '8cmx2cmx2cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Touca', 67.03, '500cmx300cmx215cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Capacete', 75.55, '8cmx2cmx2cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Arco-e-flecha', 79.88, '1mx1mx1m');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Tijolo', 28.57, '10cmx40cmx5cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Cimento', 36.28, '60cmx51cmx12cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Espátula', 72.55, '10cmx40cmx5cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Nível', 6.12, '29cmx81cmx100cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Computador', 12.1, '6cmx90cmx10cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Mouse', 27.99, '15cmx30cmx50cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Teclado', 9.64, '15cmx30cmx50cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Fita Isolante', 14.12, '15cmx30cmx50cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Fita Crepe', 29.82, '1mx1mx1m');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Fita Adesiva', 86.08, '6cmx90cmx10cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Folha Sulfite', 34.99, '15cmx30cmx50cm');
insert into materials (mtr_description, mtr_weight, mtr_dimension) values ('Impressora', 18.76, '1cmx2cmx3cm');
